name: nuxify_widgetbook_qr_scanner
description: "A new Flutter project."
publish_to: "none"
version: 1.5.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^7.1.4

dev_dependencies:
  build_runner: ^2.10.5
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
