name: widgetbook_workspace
description: "A new Flutter project."
publish_to: "none"
version: 1.7.6

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  nuxify_widgetbook_core:
    path: ../core
    # temporarily use path to import new params
    # git:
    #   url: https://github.com/Nuxify/widgetbook.git
    #   path: core
    #   ref: v1.6.0
  nuxify_widgetbook_qr_scanner:
    path: ../qr_scanner
    # temporarily use path to import new params
    # git:
    #   url: https://github.com/Nuxify/widgetbook.git
    #   path: qr_scanner
    #   ref: v1.6.0
  widgetbook: ^3.20.2
  widgetbook_annotation: ^3.9.0

dev_dependencies:
  build_runner: ^2.10.5
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  widgetbook_generator: ^3.20.1

flutter:
  uses-material-design: true
